pipeline {
    agent any

    environment {
        BACKEND_IMAGE = "campuskart-backend:latest"
        FRONTEND_IMAGE = "campuskart-frontend:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Prepare Environment') {
            steps {
                script {
                    bat '''
                    echo "--- Checking WSL Distribution ---"
                    wsl -l -v
                    
                    echo "--- Starting Minikube (if stopped) ---"
                    wsl -- bash -c "minikube status || minikube start --driver=docker"
                    
                    echo "--- Checking Minikube & Docker Status ---"
                    wsl -- bash -c "minikube status"
                    wsl -- bash -c "docker --version"
                    '''
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                script {
                    bat '''
                    echo "--- Building Backend ---"
                    wsl -- bash -c "cd backend && minikube image build -t campuskart-backend:latest ."
                    '''

                    bat '''
                    echo "--- Building Frontend ---"
                    wsl -- bash -c "cd public-view && minikube image build -t campuskart-frontend:latest ."
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                bat '''
                echo "--- Applying K8s Manifests ---"
                wsl -- kubectl apply -f k8s/mongodb.yaml
                wsl -- kubectl apply -f k8s/backend.yaml
                wsl -- kubectl apply -f k8s/frontend.yaml
                
                echo "--- Forcing Rollout to use new images ---"
                wsl -- kubectl rollout restart deployment campuskart-backend
                wsl -- kubectl rollout restart deployment campuskart-frontend
                '''
            }
        }

        stage('Verify Deployment') {
            steps {
                bat '''
                echo "--- Fetching Pods and Services ---"
                wsl -- kubectl get pods
                wsl -- kubectl get svc
                '''
            }
        }
    }

    post {
        always {
            script {
                def buildStatus = currentBuild.result ?: 'SUCCESS'
                def statusColor = buildStatus == 'SUCCESS' ? '#4CAF50' : (buildStatus == 'FAILURE' ? '#F44336' : '#FF9800')
                def subject = "CampusKart Build ${buildStatus}: ${env.JOB_NAME} [#${env.BUILD_NUMBER}]"
                def body = """
                    <html>
                    <body style="font-family: Arial, sans-serif; background-color: #f4f4f9; padding: 20px;">
                        <div style="max-width: 600px; margin: auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.1); border-top: 6px solid ${statusColor};">
                            <h2 style="color: #333; text-align: center;">CampusKart CI/CD Pipeline</h2>
                            <p style="font-size: 16px; color: #555;">Hello Prajwal,</p>
                            <p style="font-size: 16px; color: #555;">The automated build and deployment process has completed.</p>
                            
                            <div style="background-color: #f8f9fa; border-left: 4px solid ${statusColor}; padding: 15px; margin: 20px 0;">
                                <h3 style="margin: 0; color: ${statusColor}; font-size: 20px;">Status: ${buildStatus}</h3>
                                <p style="margin: 10px 0 0 0; font-size: 14px; color: #666;"><strong>Job Name:</strong> ${env.JOB_NAME}</p>
                                <p style="margin: 5px 0 0 0; font-size: 14px; color: #666;"><strong>Build Number:</strong> #${env.BUILD_NUMBER}</p>
                                <p style="margin: 5px 0 0 0; font-size: 14px; color: #666;"><strong>Branch:</strong> ${env.BRANCH_NAME ?: 'main'}</p>
                            </div>
                            
                            <p style="font-size: 14px; color: #555;">Click the button below to view the full logs and details.</p>
                            <div style="text-align: center; margin: 30px 0;">
                                <a href="${env.BUILD_URL}" style="background-color: #007bff; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;">View Build in Jenkins</a>
                            </div>
                            
                            <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                            <p style="font-size: 12px; color: #999; text-align: center;">This is an automated message generated by the CampusKart Jenkins Pipeline.</p>
                        </div>
                    </body>
                    </html>
                """

                emailext(
                    subject: subject,
                    body: body,
                    mimeType: 'text/html',
                    to: 'prajwalganiga06@gmail.com'
                )
            }
        }
    }
}
